import { useEffect, useState } from "react";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

export default function App() {
  const [documents, setDocuments] = useState([]), [files, setFiles] = useState([]), [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState(null), [error, setError] = useState(""), [busy, setBusy] = useState("");
  const refreshDocuments = async () => { const response = await fetch(`${API_URL}/documents`); if (response.ok) setDocuments(await response.json()); };
  useEffect(() => { refreshDocuments().catch(() => setError("Could not connect to the DocuQuery backend.")); }, []);
  const upload = async (event) => { event.preventDefault(); if (!files.length) return setError("Choose at least one PDF."); setError(""); setBusy("Processing document: extracting text, creating embeddings, and indexing..."); try { for (const file of files) { const form = new FormData(); form.append("file", file); const response = await fetch(`${API_URL}/documents/upload`, { method: "POST", body: form }); if (!response.ok) throw new Error((await response.json()).detail); } await refreshDocuments(); setFiles([]); event.target.reset(); } catch (e) { setError(e.message || "Upload failed."); } finally { setBusy(""); } };
  const ask = async (event) => { event.preventDefault(); setError(""); setAnswer(null); setBusy("Searching documents and generating answer..."); try { const response = await fetch(`${API_URL}/query`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail); setAnswer(body); } catch (e) { setError(e.message || "Question failed."); } finally { setBusy(""); } };
  const remove = async (id) => { await fetch(`${API_URL}/documents/${id}`, { method: "DELETE" }); await refreshDocuments(); };
  return <main><header><p className="eyebrow">LOCAL RAG DOCUMENT Q&A</p><h1>DocuQuery</h1><p>AI Document Assistant</p></header><section><h2>Upload PDFs</h2><form onSubmit={upload}><input aria-label="Choose PDF files" type="file" accept="application/pdf,.pdf" multiple onChange={(e) => setFiles([...e.target.files])} /><button disabled={!!busy}>Upload</button></form></section><section><h2>Uploaded Documents</h2>{documents.length ? <ul>{documents.map((doc) => <li key={doc.document_id}>📄 {doc.filename}<button className="delete" onClick={() => remove(doc.document_id)}>Remove</button></li>)}</ul> : <p className="muted">No documents uploaded yet.</p>}</section><section><h2>Ask a question</h2><form onSubmit={ask}><textarea value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="What would you like to know?" /><button disabled={!!busy || !question.trim()}>Ask</button></form></section>{busy && <p className="status">{busy}</p>}{error && <p className="error" role="alert">{error}</p>}{answer && <section className="answer"><h2>Answer</h2><p>{answer.answer}</p><h2>Sources</h2>{answer.sources.length ? <ul>{answer.sources.map((source, index) => <li key={`${source.filename}-${source.page}-${index}`}>📄 {source.filename} — Page {source.page}</li>)}</ul> : <p className="muted">No relevant sources found.</p>}</section>}</main>;
}
